[tool.isort]
profile = "black"
line_length = 80

import_heading_future="Future Libraries"
import_heading_stdlib="Python Standard Libraries"
import_heading_thirdparty="Third Party Libraries"
import_heading_firstparty="Project Libraries"
import_heading_localfolder="Local Folder Libraries"

force_sort_within_sections=true

[tool.black]
line_length = 80
experimental-string-processing = true

[tool.pylint.messages_control]
max-line-length = 80

[tool.pylint.variables]
good-names = ["df"]

[tool.mypy]
ignore_missing_imports = true

[tool.pydocstyle]
ignore = ["D400", "D213", "D413"]

[tool.flake8]
max-line-length = 80
exclude = [".git", "__pycache__", ".venv", ".mypy_cache", ".pytest_cache"]

